### ISSUE TITLE
The assets links are not working.

### ISSUE THREAD

**Issue by kratos2377** [math-araujo/procedural-terrain-generation#1]
The asset links does not seem to be working. Can you please update the links ?

**Comment by math-araujo** [comment]
Hey. I believe something changed on FreePBR page, as I'm not immediately able to extract the same downloadable links as before for usage via Python scripts that download the files (the image resizing scripts still works though).

You still can download the files manually until I understand what's happening:

https://freepbr.com/materials/river-rock-1/
https://freepbr.com/materials/rocky-snow-ice/
https://freepbr.com/materials/slate-rock-2-pbr-material/

Let me know if there's anything else that I can do to help you.

**Comment by kratos2377** [comment]
Thanks a lot for providing these links. I followed the instructions like
you mentioned in README.md file. But I am getting this following error. Can
you help me in fixing this issue?

**Comment by math-araujo** [comment]
Can you provide the error messages please? I believe that they are missing in your previous message.
